window.knq = [
    "Jag har aldrig ljugit för mina föräldrar.",
    "Jag har aldrig hoppat bungyjump.",
    "Jag har aldrig brutit ett ben.",
    "Jag har aldrig varit på en blinddejt.",
    "Jag har aldrig stulit något.",
    "Jag har aldrig blivit arresterad.",
    "Jag har aldrig fått parkeringsböter.",
    "Jag har aldrig svimmat.",
    "Jag har aldrig haft en crush på en lärare.",
    "Jag har aldrig skickat ett pinsamt sms till fel person.",
    "Jag har aldrig rest utanför Europa.",
    "Jag har aldrig blivit utkastad från en bar.",
    "Jag har aldrig haft en tatuering.",
    "Jag har aldrig färgat håret.",
    "Jag har aldrig kört bil utan körkort.",
    "Jag har aldrig åkt fast för fortkörning.",
    "Jag har aldrig använt dejtingappar.",
    "Jag har aldrig varit i ett långdistansförhållande.",
    "Jag har aldrig skrivit ett kärleksbrev.",
    "Jag har aldrig varit på TV.",
    "Jag har aldrig skrattat så jag gråtit.",
    "Jag har aldrig testat online dating.",
    "Jag har aldrig vunnit på lotteri.",
    "Jag har aldrig kysst någon av samma kön.",
    "Jag har aldrig ljugit för att imponera på någon.",
    "Jag har aldrig haft en övernaturlig upplevelse.",
    "Jag har aldrig tappat bort min mobiltelefon.",
    "Jag har aldrig råkat skicka ett sms som jag ångrade direkt.",
    "Jag har aldrig dansat på ett bord.",
    "Jag har aldrig missat ett flyg.",
    "Jag har aldrig haft en skäggig partner.",
    "Jag har aldrig haft en piercing.",
    "Jag har aldrig fått en dålig frisyr.",
    "Jag har aldrig varit så full att jag inte minns vad som hände.",
    "Jag har aldrig gått vilse i en annan stad.",
    "Jag har aldrig skrivit dagbok.",
    "Jag har aldrig tappat bort min plånbok.",
    "Jag har aldrig skällt ut en främling.",
    "Jag har aldrig varit på en festival.",
    "Jag har aldrig varit med i en tävling.",
    "Jag har aldrig hoppat från en klippa i vattnet.",
    "Jag har aldrig varit på en konsert.",
    "Jag har aldrig skickat ett pinsamt meddelande på sociala medier.",
    "Jag har aldrig brutit mot en lag.",
    "Jag har aldrig blivit portad från en klubb.",
    "Jag har aldrig fuskat på ett prov.",
    "Jag har aldrig hånglat på offentlig plats.",
    "Jag har aldrig spelat på en slotmaskin.",
    "Jag har aldrig kört fel i en ny stad.",
    "Jag har aldrig haft en stalker.",
    "Jag har aldrig brutit mot en trafiklag.",
    "Jag har aldrig skrattat åt något olämpligt.",
    "Jag har aldrig haft en dålig dejt.",
    "Jag har aldrig sagt något jag direkt ångrade.",
    "Jag har aldrig ätit på en Michelin-restaurang.",
    "Jag har aldrig fått en allergisk reaktion.",
    "Jag har aldrig varit på en temafest.",
    "Jag har aldrig flugit i en helikopter.",
    "Jag har aldrig pratat i sömnen.",
    "Jag har aldrig ljugit om min ålder.",
    "Jag har aldrig varit i Las Vegas.",
    "Jag har aldrig åkt på roadtrip.",
    "Jag har aldrig deltagit i ett maraton.",
    "Jag har aldrig tagit en selfie på en konstig plats.",
    "Jag har aldrig haft en tvilling.",
    "Jag har aldrig åkt båt i stormigt väder.",
    "Jag har aldrig besökt en djurpark.",
    "Jag har aldrig varit med om en jordbävning.",
    "Jag har aldrig jobbat på en restaurang.",
    "Jag har aldrig besökt ett slott.",
    "Jag har aldrig haft ett långdistansförhållande.",
    "Jag har aldrig glömt bort min väns födelsedag.",
    "Jag har aldrig vunnit en tävling.",
    "Jag har aldrig tappat bort ett viktigt dokument.",
    "Jag har aldrig använt någon annans tandborste.",
    "Jag har aldrig slagit någon med flit.",
    "Jag har aldrig använt snapchat.",
    "Jag har aldrig fallit ner från ett träd.",
    "Jag har aldrig åkt skidor.",
    "Jag har aldrig bott i ett annat land.",
    "Jag har aldrig blivit lurad av en scam.",
    "Jag har aldrig blivit stucken av en geting.",
    "Jag har aldrig gått vilse i en storstad.",
    "Jag har aldrig blivit av med passet på resa.",
    "Jag har aldrig provat att surfa.",
    "Jag har aldrig hållit ett tal.",
    "Jag har aldrig spelat gitarr.",
    "Jag har aldrig tränat kampsport.",
    "Jag har aldrig besökt en vulkan.",
    "Jag har aldrig spelat en sport professionellt.",
    "Jag har aldrig varit på en yacht.",
    "Jag har aldrig besökt en vingård.",
    "Jag har aldrig haft en sommarflirt.",
    "Jag har aldrig haft sex på första dejten.",
    "Jag har aldrig haft ett one-night stand.",
    "Jag har aldrig haft sex utomhus.",
    "Jag har aldrig kysst någon av samma kön.",
    "Jag har aldrig haft sex på en offentlig plats.",
    "Jag har aldrig fantiserat om någon på jobbet.",
    "Jag har aldrig skickat nakenbilder till någon.",
    "Jag har aldrig haft sex i en bil.",
    "Jag har aldrig tittat på porr.",
    "Jag har aldrig haft sex på stranden.",
    "Jag har aldrig pratat dirty med någon under sex.",
    "Jag har aldrig haft sex på jobbet.",
    "Jag har aldrig haft sex i duschen.",
    "Jag har aldrig gått commando.",
    "Jag har aldrig haft sex på en fest.",
    "Jag har aldrig använt handklovar under sex.",
    "Jag har aldrig haft en sexdröm om en kollega.",
    "Jag har aldrig kysst en främling.",
    "Jag har aldrig haft sex med någon mycket äldre än mig.",
    "Jag har aldrig haft sex på ett hotell.",
    "Jag har aldrig blivit påkommen under sex.",
    "Jag har aldrig hånglat med någon på en klubb.",
    "Jag har aldrig tagit på mig något extra sexigt för att imponera på någon.",
    "Jag har aldrig sextat någon.",
    "Jag har aldrig blivit smiskad under sex.",
    "Jag har aldrig haft sex med någon som jag inte visste namnet på.",
    "Jag har aldrig haft en romantisk fling på semester.",
    "Jag har aldrig kysst någon på första dejten.",
    "Jag har aldrig fått ett lap dance.",
    "Jag har aldrig gett ett lap dance.",
    "Jag har aldrig haft sex med någon i ett annat land.",
    "Jag har aldrig rollspelat under sex.",
    "Jag har aldrig testat bondage.",
    "Jag har aldrig blivit avklädd av någon annan.",
    "Jag har aldrig kysst mer än en person på samma dag.",
    "Jag har aldrig haft sex i en park.",
    "Jag har aldrig haft sex när någon annan var i rummet.",
    "Jag har aldrig haft en booty call.",
    "Jag har aldrig haft sex med någon som pratade ett annat språk.",
    "Jag har aldrig haft sex i en skog.",
    "Jag har aldrig haft sex på ett tak.",
    "Jag har aldrig haft sex i en garderob.",
    "Jag har aldrig kysst någon som jag knappt kände.",
    "Jag har aldrig haft en sexdröm om en kändis.",
    "Jag har aldrig haft sex med någon jag träffade online.",
    "Jag har aldrig varit på en stripklubb.",
    "Jag har aldrig haft sex framför en brasa.",
    "Jag har aldrig kysst någon på en utekväll och ångrat det direkt.",
    "Jag har aldrig haft sex på ett bibliotek.",
    "Jag har aldrig flirtat med någon för att få något gratis.",
    "Jag har aldrig fått ett sugmärke.",
    "Jag har aldrig blivit kysst av två personer på samma gång.",
    "Jag har aldrig fått ett samlag avbrutet av någon annan.",
    "Jag har aldrig spelat strip poker.",
    "Jag har aldrig kysst någon på en utekväll och glömt bort det.",
    "Jag har aldrig känt ånger efter sex.",
    "Jag har aldrig hånglat med någon medan någon annan tittade på.",
    "Jag har aldrig blivit ertappad medan jag hade sex.",
    "Jag har aldrig kysst någon med piercing.",
    "Jag har aldrig haft sex på en offentlig toalett.",
    "Jag har aldrig kysst någon i regnet.",
    "Jag har aldrig fått en lap dance.",
    "Jag har aldrig kysst någon i hissen.",
    "Jag har aldrig haft sex medan andra sov i samma rum.",
    "Jag har aldrig haft sex på en studsmatta.",
    "Jag har aldrig använt kläder under sex som jag inte skulle ha annars.",
    "Jag har aldrig haft sex på ett bibliotek.",
    "Jag har aldrig haft sex med mer än tre personer på samma vecka.",
    "Jag har aldrig hånglat med någon på dansgolvet.",
    "Jag har aldrig kysst någon för pengar.",
    "Jag har aldrig kysst någon i ett tält.",
    "Jag har aldrig haft sex på en brygga.",
    "Jag har aldrig haft sex med en kollega.",
    "Jag har aldrig kysst någon med skägg.",
    "Jag har aldrig haft sex när någon ringde på dörren.",
    "Jag har aldrig blivit kysst på nacken.",
    "Jag har aldrig varit den som startat ett dansgolv på en fest.",
    "Jag har aldrig druckit så mycket att jag inte minns hur jag kom hem.",
    "Jag har aldrig haft på mig en kostym eller dräkt på en fest.",
    "Jag har aldrig spelat 'Sanning eller konsekvens' på en fest.",
    "Jag har aldrig gått på en temafest.",
    "Jag har aldrig hånglat med någon på dansgolvet.",
    "Jag har aldrig dansat på ett bord på en fest.",
    "Jag har aldrig haft ett one-night stand på en fest.",
    "Jag har aldrig gått på en efterfest som var bättre än själva festen.",
    "Jag har aldrig blivit utslängd från en klubb eller bar.",
    "Jag har aldrig gjort ett spontant skinny dip på en fest.",
    "Jag har aldrig kysst någon under ett fyrverkeri.",
    "Jag har aldrig lekt en dricklek på en fest.",
    "Jag har aldrig använt glitter eller kroppsmålning på en fest.",
    "Jag har aldrig druckit ur någon annans drink.",
    "Jag har aldrig blivit packad på gratis shots.",
    "Jag har aldrig haft en fyllekonversation som jag ångrade dagen efter.",
    "Jag har aldrig blivit uppvaktad av någon på en klubb.",
    "Jag har aldrig gått hem från en fest utan mina skor.",
    "Jag har aldrig dansat hela natten till gryningen.",
    "Jag har aldrig kysst en främling på en fest.",
    "Jag har aldrig flirtat med någon för att få gratis drinkar.",
    "Jag har aldrig kysst någon som jag just mött på en fest.",
    "Jag har aldrig haft sex på en fest.",
    "Jag har aldrig blivit smiskad på en fest.",
    "Jag har aldrig deltagit i en strip poker-lek.",
    "Jag har aldrig haft sex i en jacuzzi på en fest.",
    "Jag har aldrig kysst någon i en mörklagd festlokal.",
    "Jag har aldrig spelat ett sexrelaterat sällskapsspel.",
    "Jag har aldrig gått till en fest utan att bära underkläder.",
    "Jag har aldrig gått hem med någon från en klubb.",
    "Jag har aldrig kysst någon under en dricklek.",
    "Jag har aldrig dansat utan tröja på en klubb.",
    "Jag har aldrig haft på mig latex på en fest.",
    "Jag har aldrig kysst en kompis på en fest.",
    "Jag har aldrig provat att dansa pole dance på en fest.",
    "Jag har aldrig lekt kyssleken på en fest.",
    "Jag har aldrig blivit fotad på en fest när jag gjorde något pinsamt.",
    "Jag har aldrig spelat 'Jag har aldrig' på en fest.",
    "Jag har aldrig haft sex i en bil efter en fest.",
    "Jag har aldrig kysst mer än två personer på samma fest.",
    "Jag har aldrig varit på en rave-fest.",
    "Jag har aldrig deltagit i en nyårsfest som urartade.",
    "Jag har aldrig burit handklovar på en fest.",
    "Jag har aldrig kysst någon i en fotobås på en fest.",
    "Jag har aldrig flirtat öppet med någon på en fest.",
    "Jag har aldrig fått en oväntad kyss på en fest.",
    "Jag har aldrig dansat i regnet på en utomhusfest.",
    "Jag har aldrig fått en drink spilld över mig på en fest.",
    "Jag har aldrig kysst någon i en fotobås på en klubb.",
    "Jag har aldrig deltagit i en poolfest.",
    "Jag har aldrig dansat med någon i en sexig outfit på en fest.",
    "Jag har aldrig provat body shots på en fest.",
    "Jag har aldrig dansat utan underkläder på en fest.",
    "Jag har aldrig spelat 'Never Have I Ever' på en kinky-fest.",
    "Jag har aldrig blivit påkommen när jag gjorde något intimt på en fest.",
    "Jag har aldrig haft sex i ett tält efter en festival.",
    "Jag har aldrig kysst någon under en temafest.",
    "Jag har aldrig deltagit i en dricklek som urartade.",
]

window.getQuestion = function () {
    // If there are no questions left, set it to "Slut på frågor :("
    if (window.knq.length < 1) {
        document.getElementById("question").innerHTML = "Slut på frågor :("
        return
    }
    // Get a random one from window.knq and remove it
    const index = Math.floor(Math.random() * window.knq.length);
    const question = window.knq[index];
    window.knq.splice(index, 1);
    // Set the innerHTML of the question element to the question
    document.getElementById("question").innerHTML = question;
}