window.pekq = [
    "Peka på den som alltid kommer för sent till festen.",
    "Peka på den som mest troligt kommer att bli fullast ikväll.",
    "Peka på den som brukar vara festens mittpunkt.",
    "Peka på den som brukar glömma bort vad som hände under festen.",
    "Peka på den som alltid vill dra igång en lek.",
    "Peka på den som alltid har bäst partykläder.",
    "Peka på den som mest troligt kommer att dansa hela natten.",
    "Peka på den som är bäst på att sjunga karaoke.",
    "Peka på den som har varit på flest festivaler.",
    "Peka på den som har flest pinsamma fyllehistorier.",
    "Peka på den som aldrig missar en efterfest.",
    "Peka på den som brukar somna först på fester.",
    "Peka på den som alltid hittar på de roligaste lekarna.",
    "Peka på den som alltid försöker få alla att dricka shots.",
    "Peka på den som alltid glömmer bort var de lagt sin drink.",
    "Peka på den som oftast glömmer något viktigt på festen.",
    "Peka på den som brukar vara den första att gå hem.",
    "Peka på den som oftast hamnar på dansgolvet.",
    "Peka på den som oftast glömmer var de lagt sin telefon.",
    "Peka på den som har den högsta alkoholhalten i blodet just nu.",
    "Peka på den som oftast blir utslängd från klubben.",
    "Peka på den som mest troligt kommer att dansa på ett bord.",
    "Peka på den som alltid får gratis drinkar.",
    "Peka på den som aldrig säger nej till en efterfest.",
    "Peka på den som mest troligt kommer att hångla med någon ikväll.",
    "Peka på den som oftast tappar bort sina nycklar.",
    "Peka på den som mest troligt kommer att spilla sin drink.",
    "Peka på den som brukar ta selfies hela kvällen.",
    "Peka på den som mest troligt kommer att berätta en sjuk hemlighet ikväll.",
    "Peka på den som har varit på flest fester det senaste året.",
    "Peka på den som oftast har roligast fyllehistorier att berätta.",
    "Peka på den som mest troligt kommer att skicka ett fylle-sms.",
    "Peka på den som brukar bli sentimental när de är fulla.",
    "Peka på den som brukar dansa på bardisken.",
    "Peka på den som oftast hittar kärleken på en fest.",
    "Peka på den som mest troligt kommer att somna på efterfesten.",
    "Peka på den som brukar spela den bästa musiken på fester.",
    "Peka på den som alltid är den sista som lämnar festen.",
    "Peka på den som mest troligt kommer att kyssa någon ikväll.",
    "Peka på den som alltid beställer den dyraste drinken.",
    "Peka på den som mest troligt kommer att bli utslängd från klubben ikväll.",
    "Peka på den som oftast hamnar i djupa samtal på fester.",
    "Peka på den som oftast stannar till stängning.",
    "Peka på den som har flest festbilder på sin telefon.",
    "Peka på den som mest troligt kommer att tappa bort sin plånbok ikväll.",
    "Peka på den som oftast blir mest full av alla.",
    "Peka på den som mest troligt kommer att sno DJ:s plats ikväll.",
    "Peka på den som är bäst på att improvisera danser på dansgolvet.",
    "Peka på den som oftast får sin drink spilld över sig.",
    "Peka på den som alltid startar de bästa samtalsämnena på en fest.",
    "Peka på den som är bäst på att hitta till efterfesten.",
    "Peka på den som oftast går på blinddejter.",
    "Peka på den som mest troligt kommer att hångla med en främling ikväll.",
    "Peka på den som brukar vara den första att gå till dansgolvet.",
    "Peka på den som alltid hittar en ursäkt för att slippa dricka.",
    "Peka på den som mest troligt kommer att dansa tills solen går upp.",
    "Peka på den som har mest pinsamma fyllestorys.",
    "Peka på den som brukar spilla sin drink först.",
    "Peka på den som mest troligt kommer att kyssa någon av misstag.",
    "Peka på den som mest troligt kommer att beställa en runda shots för alla.",
    "Peka på den som brukar dra de mest pinsamma skämten på fester.",
    "Peka på den som alltid blir fotad i pinsamma situationer.",
    "Peka på den som alltid har bäst festsnacks.",
    "Peka på den som oftast vinner i drickspel.",
    "Peka på den som mest troligt kommer att dansa i regnet på en utomhusfest.",
    "Peka på den som brukar somna på soffan innan festen är över.",
    "Peka på den som alltid hittar på det bästa festen.",
    "Peka på den som alltid vet var efterfesten är.",
    "Peka på den som har flest bilder med kändisar från fester.",
    "Peka på den som mest troligt kommer att bli kär på en fest.",
    "Peka på den som alltid spelar för mycket musik från 90-talet på fester.",
    "Peka på den som alltid lyckas hamna i trubbel på en fest.",
    "Peka på den som mest troligt kommer att komma överklädd till festen.",
    "Peka på den som oftast kommer med bästa dansmoves.",
    "Peka på den som alltid tar med den starkaste spriten.",
    "Peka på den som mest troligt kommer att avslöja en hemlighet ikväll.",
    "Peka på den som mest troligt kommer att gå hem med någon okänd.",
    "Peka på den som alltid fixar den bästa partystämningen.",
    "Peka på den som brukar spela 'Jag har aldrig' på fester.",
    "Peka på den som alltid bjuder på rundor.",
    "Peka på den som är mest äventyrlig på fester.",
    "Peka på den som mest troligt kommer att snubbla på dansgolvet.",
    "Peka på den som alltid har de galnaste fyllehistorierna.",
    "Peka på den som brukar gå hem med någon från varje fest.",
    "Peka på den som oftast blir mest sentimental när de dricker.",
    "Peka på den som brukar gå hem tidigt från festen.",
    "Peka på den som mest troligt kommer att göra något de ångrar ikväll.",
    "Peka på den som brukar ha de vildaste sexhistorierna från fester.",
    "Peka på den som oftast blir kvar sist på efterfesten.",
    "Peka på den som alltid får flest komplimanger för sin outfit.",
    "Peka på den som brukar ta hem någon från en klubb.",
    "Peka på den som alltid flirtar mest när de är fulla.",
    "Peka på den som alltid har galna teman för sina fester.",
    "Peka på den som mest troligt kommer att dansa utan tröja ikväll.",
    "Peka på den som alltid råkar spilla sin drink.",
    "Peka på den som alltid gör bort sig på dansgolvet.",
    "Peka på den som mest troligt kommer att kyssa en främling ikväll.",
    "Peka på den som mest troligt kommer att stanna tills stängning.",
    "Peka på den som brukar spela den bästa musiken på efterfesten.",
    "Peka på den som mest troligt kommer att somna i en taxi ikväll.",
    "Peka på den som alltid börjar dansa först.",
    "Peka på den som alltid fixar den bästa stämningen på dansgolvet.",
    "Peka på den som brukar snubbla på sina klackar på dansgolvet.",
    "Peka på den som mest troligt kommer att släppa sin drink ikväll.",
    "Peka på den som oftast har bästa festen i sitt hem.",
    "Peka på den som är mest benägen att skicka ett sms de ångrar.",
    "Peka på den som alltid har något roligt att berätta.",
    "Peka på den som mest troligt kommer att sjunga med högst röst till en nostalgisk låt.",
    "Peka på den som alltid får komplimanger för sitt skratt.",
    "Peka på den som mest troligt kommer att dansa med en främling ikväll.",
    "Peka på den som alltid har bästa festtipsen.",
    "Peka på den som oftast bjuder in till förfest.",
    "Peka på den som mest troligt kommer att hångla med två personer samma kväll.",
    "Peka på den som mest troligt kommer att ta av sig kläderna på dansgolvet.",
    "Peka på den som brukar bli DJ på alla fester.",
    "Peka på den som oftast försvinner från festen utan att säga hejdå.",
    "Peka på den som mest troligt kommer att sno någon annans drink.",
    "Peka på den som alltid startar ett drickspel.",
    "Peka på den som mest troligt kommer att gå hem med någon ikväll.",
    "Peka på den som alltid har roligast på fester.",
    "Peka på den som alltid är den mest högljudda på festen.",
    "Peka på den som oftast går vilse på väg hem från klubben.",
    "Peka på den som mest troligt kommer att tappa bort sitt ID ikväll.",
    "Peka på den som alltid har bäst drinkidéer.",
    "Peka på den som brukar överdriva sina fyllehistorier.",
    "Peka på den som alltid är snabbast på att beställa nästa runda.",
    "Peka på den som oftast slutar dansa först.",
    "Peka på den som mest troligt kommer att släppa sin drink på någon annan.",
    "Peka på den som oftast dricker mest på kortast tid.",
    "Peka på den som alltid verkar ha oändlig energi på dansgolvet.",
    "Peka på den som oftast säger att de ska gå hem men stannar ändå.",
    "Peka på den som mest troligt kommer att spilla på någon annans kläder.",
    "Peka på den som oftast skickar pinsamma fylle-sms.",
    "Peka på den som alltid startar dramat på festen.",
    "Peka på den som mest troligt kommer att börja gråta ikväll.",
    "Peka på den som alltid får bäst komplimanger för sin outfit.",
    "Peka på den som oftast försvinner utan förvarning från festen.",
    "Peka på den som alltid försöker starta en gemensam skål.",
    "Peka på den som brukar hitta på nya lekar mitt i festen.",
    "Peka på den som mest troligt kommer att ringa ett fyllesamtal.",
    "Peka på den som alltid tar snyggast selfies på festen.",
    "Peka på den som mest troligt kommer att ramla omkull på dansgolvet.",
    "Peka på den som alltid är bäst på att mingla.",
    "Peka på den som oftast snor någon annans cigarett.",
    "Peka på den som mest troligt kommer att förlora sitt bankkort ikväll.",
    "Peka på den som oftast börjar prata om gamla ex när de dricker.",
    "Peka på den som brukar bli mest filosofisk på fyllan.",
    "Peka på den som mest troligt kommer att skicka fyllebilder på sig själv till någon.",
    "Peka på den som alltid fixar den roligaste förfesten.",
    "Peka på den som alltid startar de mest pinsamma fyllehistorierna.",
    "Peka på den som mest troligt kommer att ringa någon de ångrar imorgon.",
    "Peka på den som alltid lyckas charma bartenders för gratis drinkar.",
    "Peka på den som brukar ha svårast att hitta hem från en fest.",
    "Peka på den som alltid dansar med störst inlevelse.",
    "Peka på den som oftast beställer för mycket mat efter festen.",
    "Peka på den som mest troligt kommer att somna på någons axel ikväll.",
    "Peka på den som alltid vet hur man festar på bästa sätt.",
    "Peka på den som mest troligt kommer att börja bråka med dörrvakten.",
    "Peka på den som brukar gå vilse i sitt eget kvarter på väg hem från festen.",
    "Peka på den som mest troligt kommer att få ett fylleminne imorgon.",
    "Peka på den som oftast tappar sina saker på festen.",
    "Peka på den som alltid får fler gratis drinkar än alla andra.",
    "Peka på den som alltid gör pinsamma saker på fester.",
    "Peka på den som mest troligt kommer att skrika till en låt på dansgolvet ikväll.",
    "Peka på den som alltid är bäst på att hitta bästa dansmoves.",
    "Peka på den som oftast får sin drink spilld av någon annan.",
    "Peka på den som alltid tar den längsta vägen hem från klubben.",
    "Peka på den som alltid har de vildaste historierna från sina fester.",
    "Peka på den som oftast tar över DJ-båset.",
    "Peka på den som mest troligt kommer att smita från betalningen ikväll.",
    "Peka på den som oftast står och snackar istället för att dansa.",
    "Peka på den som alltid får sista ordet i ett fylledrama.",
    "Peka på den som oftast går hem med någon ny från festen.",
    "Peka på den som mest troligt kommer att vakna och inte veta var de är.",
    "Peka på den som alltid tappar bort sin väska på festen.",
    "Peka på den som brukar överraska alla med sina danssteg.",
    "Peka på den som mest troligt kommer att sjunga karaoke ikväll.",
    "Peka på den som alltid har bäst partytrick.",
    "Peka på den som mest troligt kommer att komma överklädd till festen.",
    "Peka på den som oftast får någon annans drink över sig.",
    "Peka på den som alltid fixar den bästa musiklistan.",
    "Peka på den som oftast blir fotad i pinsamma situationer.",
    "Peka på den som brukar försvinna från festen och dyka upp igen på efterfesten.",
    "Peka på den som mest troligt kommer att glömma vad de gjort imorgon.",
    "Peka på den som alltid startar ett fyllebråk.",
    "Peka på den som mest troligt kommer att hamna i ett drama ikväll.",
    "Peka på den som alltid har mest galna festplaner.",
    "Peka på den som mest troligt kommer att bli bjuden på drinkar hela kvällen.",
    "Peka på den som mest troligt kommer att kyssa någon de knappt känner ikväll.",
    "Peka på den som alltid får komplimanger för sina moves på dansgolvet.",
    "Peka på den som mest troligt kommer att dansa tills de stupar.",
    "Peka på den som alltid har de konstigaste historierna från fester.",
    "Peka på den som oftast får beröm för sin outfit på fester.",
    "Peka på den som mest troligt kommer att råka spilla sin drink ikväll.",
    "Peka på den som alltid är den sista som lämnar festen.",
    "Peka på den som oftast är festens största överraskning.",
    "Peka på den som mest troligt kommer att bli kär i en främling ikväll.",
    "Peka på den som alltid lyckas sno DJ:s plats.",
    "Peka på den som mest troligt kommer att somna först på efterfesten.",
    "Peka på den som alltid hamnar i de roligaste samtalen på festen.",
    "Peka på den som mest troligt kommer att bli för full och gå hem tidigt.",
    "Peka på den som alltid har bäst danssteg på festen.",
    "Peka på den som mest troligt kommer att avslöja sina djupaste hemligheter ikväll.",
    "Peka på den som alltid bjuder på rundor på fester.",
    "Peka på den som alltid hittar bästa platsen på dansgolvet.",
    "Peka på den som mest troligt kommer att skratta tills de gråter ikväll.",
    "Peka på den som alltid kommer med den bästa stämningen till festen.",
    "Peka på den som mest troligt kommer att glömma sin väska någonstans.",
    "Peka på den som alltid tar den roligaste selfiegruppen.",
    "Peka på den som mest troligt kommer att ringa ett pinsamt fyllesamtal."
]

window.getQuestion = function() {
    // If there are no questions left, set it to "Slut på frågor :("
    if (window.pekq.length < 1){
        document.getElementById("question").innerHTML = "Slut på påståenden :("
        return
    }
    // Get a random one from window.knq and remove it
    const index = Math.floor(Math.random() * window.pekq.length);
    const question = window.pekq[index];
    window.pekq.splice(index, 1);
    // Set the innerHTML of the question element to the question
    document.getElementById("question").innerHTML = question;
}